{% set name = "flask-oidc" %}
{% set version = "2.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: "84997b3b955f2168b83c097d9e6c6afbcfbb04867e08fad1d5e6b22478618485"

build:
  noarch: python
  number: 0
  entry_points:
    - oidc-register=flask_oidc.registration_util:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - flask
    - pip
    - python >=3.6
  run:
    - flask
    - itsdangerous
    - oauth2client
    - python >=3.6
    - six

test:
  imports:
    - flask_oidc
  commands:
    - oidc-register --help


about:
  home: "https://github.com/puiterwijk/flask-oidc"
  license: "BSD-2-Clause"
  license_family: "BSD"
  license_file: "LICENSE.txt"
  summary: "OpenID Connect extension for Flask"
  description: |
    Flask-OIDC is an extension to Flask that allows you to add OpenID
    Connect based authentication to your website in a matter of minutes.

  doc_url: "https://flask-oidc.readthedocs.io/"
  dev_url: "https://github.com/puiterwijk/flask-oidc"

extra:
  recipe-maintainers:
    - mxr-conda
